- data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/magic_of_faerun/mag_templates.lst
Created a Magic Spark temporary bonus.
> Magic Spark

- data/35e/wizards_of_the_coast/supplement/monster_manual_4/mm4_abilities_race.lst
- data/35e/wizards_of_the_coast/supplement/monster_manual_4/mm4_races.lst
- data/35e/wizards_of_the_coast/supplement/monster_manual_4/monster_manual_4.pcc
Added the MM4 book and the Justice Archon entry.
> Justice Archon

- data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/lost_empires_of_faerun/_lost_empires_of_faerun.pcc
- data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/lost_empires_of_faerun/le_deities.lst
- data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/lost_empires_of_faerun/le_equip_general.lst
- data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/lost_empires_of_faerun/le_equip_magic.lst
- data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/lost_empires_of_faerun/le_equipmods.lst
Added the dead gods, magical scepters (with builder), and some of the
magical items.
> Lost Empires update

- outputsheets/d20/5e/pdf/common_sheet/block_attack5e.xslt
- outputsheets/d20/5e/pdf/common_sheet/block_hp_defense5e.xslt
- outputsheets/d20/5e/pdf/common_sheet/block_misc5e.xslt
- outputsheets/d20/5e/pdf/common_sheet/block_pc_header_row5e.xslt
- outputsheets/d20/5e/pdf/common_sheet/block_weapons5e.xslt
- outputsheets/d20/5e/pdf/csheet_JD_fantasy_std_blue_light.xslt
- outputsheets/d20/5e/pdf/fantasy_master_common_blocks1.xslt
Remove some unused references on 5e PDF output sheet
> Remove some unused references on 5e PDF output sheet

- data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/races_of_faerun/_races_of_faerun.pcc
fixed dupe entry for drow poison
> fix dupe entry for Drow Poison

- data/35e/wizards_of_the_coast/web/fey_feature/_fey_feature.pcc
fix for duplication of Gray Portrait
> fixed gray portrait in FF

- data/35e/wizards_of_the_coast/supplement/complete_adventurer/_complete_adventurer.pcc
Include feats for Complete Adventurer
> fixed missing ABILITY: tag in cat pcc file

- data/35e/wizards_of_the_coast/supplement/complete_champion/cc_abilities.lst
fix deprecated use of CHOOSE:SCHOOLS
> added |ALL to CHOOSE:SCHOOLS

- data/35e/wizards_of_the_coast/supplement/complete_champion/README-church.txt
- data/35e/wizards_of_the_coast/supplement/complete_champion/cc_abilities.lst
Feature request #519
Implemented the Shining Light of Pelor.
> [dnd 3.5] Complete Champion, Church, implement The Shining Light of Pelor

- data/35e/wizards_of_the_coast/supplement/complete_champion/README-church.txt
- data/35e/wizards_of_the_coast/supplement/complete_champion/cc_abilities.lst
> [dnd 3.5] Complete Champion, Church, Fharlanghn's Way #542

- data/35e/wizards_of_the_coast/supplement/complete_psionic/cp_classes.lst
Correct Divine Mind's Caster and Manifester Levels
> Correct Divine Mind's Caster and Manifester Levels

- data/35e/wizards_of_the_coast/supplement/libris_mortis/lm_abilities.lst
- data/35e/wizards_of_the_coast/supplement/libris_mortis/lm_abilitycategories.lst
- data/35e/wizards_of_the_coast/supplement/libris_mortis/lm_templates.lst
Additions to the Libris Mortis to include the templates and abilities
for Corpsecrafted undead.
> Corpsecrafted

- data/5e/wizards_of_the_coast/core/players_handbook/ph_equip.lst
Added Type:Spellbook to the Spellbook item to enable adding spells to owned Spellbooks
> Added Spellbook type to Spellbook

- data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/races_of_faerun/rac_templates.lst
Added a region for Gnolls in Thayan following the region templates in
the Players Guide to Faerun.
> ThayanGnollRegion

- data/35e/paizo/dragon_magazine/313/DragonMagazine313.pcc
- data/35e/paizo/dragon_magazine/313/dm313_abilities.lst
- data/35e/paizo/dragon_magazine/313/dm313_template.lst
Ran in the half-undead templates: fetch, gheden, ghul, and katane.
> DragonMagazine313HalfUndead

- data/35e/wizards_of_the_coast/supplement/book_of_exalted_deeds/be_spells.lst
Added the pre-reqs for the Exalted Spells (non-evil align and memorized
only).
> BE_ExaltedSpells

- data/35e/wizards_of_the_coast/supplement/book_of_exalted_deeds/be_equipmods.lst
Added the arcane spellcasting failure reduction to the Twilight
equipment mod.
> BE_TwilightEquipmodFix

- data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/lost_empires_of_faerun/le_class_abilities.lst
Updated the class abilities file to adjust TYPE values for
Extraordinary, Supernatural, and SpellLike designations.
> LE_ClassFeatureAbilityTypes

- data/5e/wizards_of_the_coast/campaign/forgotten_realms/sword_coast_adventurers_guide/scag_equip.lst
fixes #828 
by adding Coin ([name]) formatting
and also removes duplicate entries
> reformatted names to reflect core PHB

- data/35e/wizards_of_the_coast/supplement/stormwrack/_stormwrack.pcc
- data/35e/wizards_of_the_coast/supplement/stormwrack/sto_abilitycategories.lst
- data/35e/wizards_of_the_coast/supplement/stormwrack/sto_class_abilities.lst
- data/35e/wizards_of_the_coast/supplement/stormwrack/sto_classes.lst
Added the Scarlet Corsair and the Stormcaster classes.
> STO_Classes

- data/35e/wizards_of_the_coast/campaign_settings/forgotten_realms/unapproachable_east/una_spells.lst
modify the description of certain spells - only when selected by the runescarred berserker class - to add the cost.
> Runescarrcost

- .gitignore
- data/35e/wizards_of_the_coast/supplement/magic_item_compendium/mic_equip.lst
just updating the output description
> Add sprop bedroll

- data/35e/wizards_of_the_coast/supplement/tome_of_magic/tm_classes.lst
Added missing Base Reflex Save value for Binder.
> Fixed Binder reflex save calculation and missing bonus feats

- data/35e/wizards_of_the_coast/campaign_settings/dragonlance/races_of_ansalon/roa_equip_arms_armor.lst
removed invalid characters and corrected to quotes.
> clean ArmsEquip source

- data/35e/wizards_of_the_coast/supplement/complete_warrior/cw_classes.lst
War Chanter PrC had Bardic Inspire Courage as a prerequisite and it should be Bardic Music ~ Inspire Courage.
> War Chanter Fix
